allowBuilds:
  '@google/genai': true
  '@prisma/client': true
  '@prisma/engines': true
  '@whiskeysockets/baileys': true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  protobufjs: true
onlyBuiltDependencies:
  - "@google/genai"
  - "@prisma/client"
  - "@prisma/engines"
  - "@whiskeysockets/baileys"
  - "esbuild"
  - "msgpackr-extract"
  - "prisma"
  - "protobufjs"
